### ISSUE TITLE
latest Version don't spawn Missions (Exile)

### ISSUE THREAD

**Issue by BdMdesigN** [IT07/ArmA3_exile_vemf_reloaded#3]
I have the problem in Exile 1.0.0 and Infistar v0054, thats with the latest version no Missions spawn.

With the Version befor i have no problems.
In my Logs it seen thats VemF start as it should.

**Comment by IT07** [comment]
Does VEMFr show that the missionTimer has started?

**Comment by BdMdesigN** [comment]
Yes, in my log it seens that it runs as it schould but the mission are not spawning.
I will try your latest Version and post the log via pastebin here.

The second is, now i'm on InfiStar v0055. Maybe it was Infistar.

**Comment by IT07** [comment]
It would be very unlikely that infiSTAR prevents missions from spawning.

**Comment by IT07** [comment]
Does the latest VEMFr version fix the problem you experienced?

**Comment by BdMdesigN** [comment]
@No. If are two players on the server only 2 Missions will spawn. If i'm alone on the the server 0 missions spawn.
But missions should spawn if are 0 players on the server and max 7 missions.
I will post log and config later in the exile Thread.

**Comment by IT07** [comment]
I assume you have set minPlayers to 0?

**Comment by BdMdesigN** [comment]
Yes, i found the "Bug": it was the Function "skipDistanceReversed".
If i set the function "skipDistanceReversed" in the last exile_vemf (not a3_vemf) on 50 the function don't work at it should and it's spawns everywhere missions but not 50 meters near the player.

In the newwer Versions (all new a3_vemf) this function did what it should do and this was the reason, why i thought it dosen't work because im standing in the SZ Airfield.

Now we can close this here, because the Addon works like a charme. Sorry for waste your time.
