### ISSUE TITLE
base attak erreur messages

### ISSUE THREAD

**Issue by LangeBlonds** [IT07/ArmA3_exile_vemf_reloaded#4]
hi, I'm french
google is my friend
but suddenly exile with gods that are owner goes well
I have a big concern
when a base attack missions launches I will message appears:

![20160828192117_1](https://cloud.githubusercontent.com/assets/21159246/18075229/31e702b6-6e73-11e6-8532-ad7cfb49e942.jpg)

I'm still in Exile 1.0.0

**Comment by IT07** [comment]
Update to the latest version.
