### ISSUE TITLE
File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34

### ISSUE THREAD

**Issue by koriaba** [IT07/ArmA3_exile_vemf_reloaded#6]
Hi. is such a record

[spo='my arma3server_2312_2016-09-09_11-24-09.rpt']

14:16:28 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:16:38 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:38 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:38 Error Undefined variable in expression: _this2
14:16:38 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:16:43 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:43 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:43 Error Undefined variable in expression: _this2
14:16:43 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:16:48 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:48 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:48 Error Undefined variable in expression: _this2
14:16:48 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:16:53 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:53 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:53 Error Undefined variable in expression: _this2
14:16:53 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:16:58 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:58 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:16:58 Error Undefined variable in expression: _this2
14:16:58 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:17:33 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:17:33 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:17:33 Error Undefined variable in expression: _this2
14:17:33 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:17:44 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:17:44 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:17:44 Error Undefined variable in expression: _this2
14:17:44 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:17:49 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:17:49 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:17:49 Error Undefined variable in expression: _this2
14:17:49 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:17:59 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:17:59 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:17:59 Error Undefined variable in expression: _this2
14:17:59 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:18:19 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:19 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:19 Error Undefined variable in expression: _this2
14:18:19 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:18:24 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:24 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:24 Error Undefined variable in expression: _this2
14:18:24 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:18:29 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:29 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:29 Error Undefined variable in expression: _this2
14:18:29 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:18:39 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:39 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:39 Error Undefined variable in expression: _this2
14:18:39 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
14:18:44 Error in expression < ] };
private _arr = nearestLocations [ _this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:44 Error position: <_this2, _t, if ( _ms0 > 0 ) then { _ms0 >
14:18:44 Error Undefined variable in expression: _this2
14:18:44 File a3_vemf_reloaded\fn\fn_findPos.sqf, line 34
[/spo]

**Comment by IT07** [comment]
That error is not enough for me to know where the cause of the error is. Tell me what kind of issues you are experiencing with VEMFr.

**Comment by koriaba** [comment]
No special problems are not present, only the entry in the error log, and it works.
There is a problem with a headless client, should there be any additional files? To this error is irrelevant.

**Comment by IT07** [comment]
I have found a possible cause of the error: no players online exactly when a DynamicLocationInvasion was launched. The chance is low but it is not entirely impossible. Can you provide any proof that there were in fact no players online at the time of the error?

**Comment by koriaba** [comment]
sure I can.
I connect - error appears, players are no longer on the server.
Thank you for your attention!
my settings [config.cpp](https://www.dropbox.com/s/bpxp8e3zxg5d3dm/config.cpp?dl=0)
[arma3server_2312_2016-09-10_10-01-00.rpt](https://www.dropbox.com/s/be1emlji19rxwvp/arma3server_2312_2016-09-10_10-01-00.rpt?dl=0)

**Comment by IT07** [comment]
Thank you for sending me your config.cpp. I have found the cause of the error: minPlayers is set to 0. I will include a warning into the next update that tells the user not to set minPlayers to a number of less than 1. Setting minPlayers to 1 will fix said error.

**Comment by koriaba** [comment]
It is very good!
Thank you for your wonderful mod!

**Comment by IT07** [comment]
Thank you.
